### ISSUE TITLE
Crashing when using placeables

### ISSUE THREAD

**Issue by MaddyPhi** [loki79uk/LumberJack#3]
So, I recently developed a mod, Automatic Storage. One of my users reported to me today that when they would place the buildings, they would no longer be able to use super strength. I managed to replicate and isolate the problem even further on my own and identified that it was not dependent on my mod but rather any placeable.

If you go into the placeables in the shop and select an item to place go to the placement screen then back out, you should find that you are no longer able to use super strength. Another way I found to cause this problem is when you sell a placeable and it is removed. This will result in the same loss of strength. The only commonality I was able to identify was that both the temporary instance of the placeable on the placement screen and the sell call the delete function of the placeable. Perhaps the problem stems there. But, I would not presume to know whether this has anything to do with your mod. I just now that I was able to replicate it in this fashion repeatedly with only the lumberjack mod, DLCs and easy dev installed.

If there is anything further I can do to help then please feel free to let me know.

Sincerely,

Madison.

**Comment by MaddyPhi** [comment]
P.S. Love this mod and the sleep anywhere mod. They are in my must-have-every-game pack of mods. You do an amazing job and your scripts are very clean and elegant.

**Comment by loki79uk** [comment]
Hi, thanks for letting me know.  I saw your message early this morning, but I have only just finished work!  I'll look at this as soon as I can.

**Comment by loki79uk** [comment]
Hi, I have reproduced the problem exactly as you describe, and also found from debugging output that (after entering the placement screen) the lumberjack toggle strength key binding is removed from the `g_inputBinding.eventBindings` table.

It seems that the game removes the player action events when you enter the placement screen, but the lumberjack key is not restored with the others (movement, crouch, etc) afterwards.  I will have to look more tomorrow, but at least I've found the cause.

**Comment by MaddyPhi** [comment]
Glad you were able to identify it and found my description sufficient.

**Comment by loki79uk** [comment]
Hopefully this has fixed it: [v2.0.3.0](https://github.com/loki79uk/LumberJack/releases/tag/v2.0.3.0)

The toggle super-strength key works for me with this version (after going in and out of the building placement screen).  If you could also test it for me before I submit to ModHub that would be awesome, but otherwise don't worry!

_N.B.: it shows how much I use super-strength (or maybe how often I place buildings) to have never noticed this behaviour before.._

**Comment by MaddyPhi** [comment]
Sure thing, I will give it a try after supper if that is okay.

**Comment by loki79uk** [comment]
> Sure thing, I will give it a try after supper if that is okay.

Did you find any issues?  I tried a few games in multiplayer and it still worked for both host and client.

**Comment by MaddyPhi** [comment]
Terribly sorry. I marked this read in my email fully intending to come back to it then forgot. I was not able to recreate the problem with your updates.

**Comment by loki79uk** [comment]
Don't worry, I do the same thing with my emails all the time! :D  Glad it is working for you too, I will submit the update to ModHub.
