### ISSUE TITLE
Can't pickup, jump,crouch,toggle flashlight, or pull out tools.

### ISSUE THREAD

**Issue by kingslycamben** [loki79uk/LumberJack#4]
This is on a multiplayer server, im hosting playing with one other person, it works completely fine for them.
[log.txt](https://github.com/loki79uk/LumberJack/files/7151441/log.txt)

**Comment by loki79uk** [comment]
Hi, thanks for letting me know!  From the log this looks like a conflict with Manure System.  Can you possibly try a game without that loaded to confirm.

There was a (similar) conflict in an old version that stopped Manure System from connecting hoses, does that still work for you?

It could potentially be related to the LumberJack fix the other week (v2.0.3.0). Was everything working for you before that (with v2.0.2.0)?

**Comment by kingslycamben** [comment]
It hasn't happened again but this issue is very rare for me, a restart fixes it but i will inform you if it happens again.

**Comment by loki79uk** [comment]
I've not had any more reports of this error.  Closing.
